### ISSUE TITLE
Clair test results are not updated in the project results page

### ISSUE THREAD

**Issue by edagan** [eedevops/shipyard#111]
Scenario (on the dev staging machine):
Added Golang:1.5 image to a project.
Added a clair test for above image
Triggered the test
Clicked ILM
Clicked the Project's magnifying glass to view results.
No results for the project even after 10+ minutes.

Tested in private env. Verified clair results are returned, at least according to the log:
`controller_1**   | time="2016-05-17T16:38:38Z" level=error msg="Image golang:1.5 is NOT safe :("
controller_1   | time="2016-05-17T16:38:40Z" level=debug msg="GET: /api/projects/bec817c2-cd8a-463a-823b-486d4db510a5/tests/ae512ab3-bda1-496b-a596-e59849e87509/builds/f104f3ff-1c11-4514-8bd4-261658e2e5a3"
clair_1        | 2016-05-17 16:38:40.872471 I | updater: adding metadata to vulnerabilities
controller_1   | time="2016-05-17T16:39:23Z" level=debug msg="GET: /api/projects/bec817c2-cd8a-463a-823b-486d4db510a5/tests/ae512ab3-bda1-496b-a596-e59849e87509/builds/279045cd-f631-4289-8d9e-93382b1d3f80/results"
controller_1   | time="2016-05-17T16:41:41Z" level=debug msg="GET: /api/projects/bec817c2-cd8a-463a-823b-486d4db510a5/tests/ae512ab3-bda1-496b-a596-e59849e87509/builds/f104f3ff-1c11-4514-8bd4-261658e2e5a3"`

**Comment by rqc** [comment]
@edagan are you still experiencing these issues? There have been major fixes and improvements with the db communication in the past 7-10 days.

**Comment by soninob** [comment]
@edagan - is this still relevant, or can we close it?
