### ISSUE TITLE
[UI] Please add a refresh button to a Project Results view

### ISSUE THREAD

**Issue by edagan** [eedevops/shipyard#112]
Such a button is sourly missed, for quickly refreshing a project's results view, without refreshing the whole URL via the browser's refresh button.

Maybe add a Refresh timer too?

**Comment by JonathanRosado** [comment]
@edagan I'll do a quick PR for this

**Comment by soninob** [comment]
@JonathanRosado - do you have something, or should I address it to @AndreeaDora as well?

**Comment by soninob** [comment]
PR #125 was merged.
