### ISSUE TITLE
[Backend] Some images (Jenkins) cause ILM to hang

### ISSUE THREAD

**Issue by JonathanRosado** [eedevops/shipyard#115]
Quite a few images, like Jenkins:latest, cause ILM to hang upon build.

Specifically, it hangs while trying to get the Build object from the database.
```Go
func (m DefaultManager) GetBuildById(buildId string) (*model.Build, error) {
	res, err := r.Table(tblNameBuilds).Filter(map[string]string{"id": buildId}).Run(m.session)
	if err != nil {
		return nil, err
	}
	if res.IsNil() {
		return nil, ErrBuildDoesNotExist
	}
	var build *model.Build
--->	if err := res.One(&build); err != nil {
		return nil, err
	}
	return build, nil
}
```

**Comment by rqc** [comment]
@JonathanRosado we had run into this issue before when trying to solve the test status synchronization. There is definitely something funky with `gorethink` and these goroutines we are creating.

**Comment by JonathanRosado** [comment]
@rqc A few people have had similar issues. This [person](https://github.com/dancannon/gorethink/issues/180), for instance, had trouble with `res.One()` only after several queries. Adding `res.Close()` fixed it for him.

**Comment by rqc** [comment]
@JonathanRosado go ahead and revise ALL manager funcs that use `gorethink` to close the appropriate descriptors.

**Comment by JonathanRosado** [comment]
@rqc Done #119
