### ISSUE TITLE
Leaky form for images after dropdown changes.

### ISSUE THREAD

**Issue by rqc** [eedevops/shipyard#149]
When I open the modal form to create a new image, if I choose to create a *private registry* image and then after selecting the fields, I decide to instead add a *public registry* image (clicking the dropdown on the left screen), what happens is that the *public registry* image will be sent to the API with the `registryId` and the `registryDomain` fields set to the previous values of the *private registry* image. Therefore, this causes an error when executing a test for that particular image because that image `domainName` + `namespace` + `tag` won't exist (most likely). 

Here is an example of the leaky image entry in the `rethinkdb` for the `alpine.3.3` image from DockerHub (note the `registryId` and `registryDomain` fields are set):

```json
{
"description": "A minimal Docker image based on Alpine Linux with a complete package index and only 5 MB in size!" ,
"id":  "57ec5257-b972-4d7f-823b-76765a84b425" ,
"ilmTags": [ ],
"imageId":  "" ,
"location":  "Public Registry" ,
"name":  "alpine" ,
"projectId":  "f3e65f4e-8f81-416c-8b0a-5b0806b1d626" ,
"registryDomain":  "ec2-52-35-14-98.us-west-2.compute.amazonaws.com:6000" ,
"registryId":  "a300ca3f-783e-4b42-b417-3305fba0b125" ,
"skipImageBuild": false ,
"tag":  "3.3"
}
```

@AndreeaDora please look at the UI side of this. Checkout the screencast below:

![bug](https://cloud.githubusercontent.com/assets/89690/16157982/01a332d8-3489-11e6-84ee-2072b5055236.gif)

@JonathanRosado please take a look at the backend side of this issue, since the backend is not failing appropriately during the build, and the status is never set to `failed`.

**Comment by soninob** [comment]
PR #167 was merged.
