### ISSUE TITLE
Docker Hub API returns empty tags array for some images

### ISSUE THREAD

**Issue by rqc** [eedevops/shipyard#151]
Docker Hub v1 is deprecated, need to switch to Docker Hub v2. Confirmed by contacting Docker support.

**Comment by rqc** [comment]
From Docker support:

> The V1 API is deprecated although some of the endpoints still work correctly there are some issues with it.
> 
> Here are a couple of example scripts:
> 
> https://gist.github.com/kizbitz/e59f95f7557b4bbb8bf2
> https://gist.github.com/kizbitz/175be06d0fbbb39bc9bfa6c0cb0d4721

**Comment by soninob** [comment]
PR #171 was merged.
