### ISSUE TITLE
Vulnerability Report in `ResultEntries` excludes vulnerability name

### ISSUE THREAD

**Issue by rqc** [eedevops/shipyard#37]
From here https://github.com/eedevops/shipyard/blob/dev/checker/checker.go#L172-L185 

It can be seen that we are just adding the `Feature` information. However, we should also add other fields, the most important being the `Name` in the `Vulnerability` object as they do here https://github.com/eedevops/shipyard/blob/dev/checker/checker.go#L146 

Thanks!

**Comment by borzamircea** [comment]
From what I can tell they are nested: Report -> [ ] Features, each Feature -> [ ] Vulnerabilities, each Vulnerability  -> Name.

So you would have:
```
for f := range Report.Features
      for v := range f.Vulnerabilities
           fmt.Printf(v.Name)
```

So we do add the names, but in a more nested, complicated manner.

**Comment by rqc** [comment]
What I'm looking for is the `CVExxxx` code. That's actually not being added.

**Comment by rqc** [comment]
FIxed here https://github.com/eedevops/shipyard/commit/6f64199ef03523ba44234146b71295d1a67923a4
