### ISSUE TITLE
Spinner for requests is not reset when changing tab views

### ISSUE THREAD

**Issue by rqc** [eedevops/shipyard#51]
If I make a call that takes a long time and I get the spinner:

![image](https://cloud.githubusercontent.com/assets/89690/14925185/26235bec-0e14-11e6-97d7-9927b85864f8.png)

and then I switch to a different tab, the spinner is not reset and I cannot use any of the controls in those views.

![image](https://cloud.githubusercontent.com/assets/89690/14925207/4a7e0168-0e14-11e6-9385-0c8ee5f7d16c.png)

**Comment by rqc** [comment]
@JonathanRosado @AndreeaDora @soninob please revise.

**Comment by JonathanRosado** [comment]
@rqc This may no longer be an issue with the new additions.

**Comment by rqc** [comment]
We haven't been able to reproduce this, so I am closing it for now.
