### ISSUE TITLE
[UI] - Tool-tip message should change after pressing the Q mark

### ISSUE THREAD

**Issue by soninob** [eedevops/shipyard#53]
When disabling verification in the edit view, we need to change the message "Click the slider to **disable** image verification." - if the verification is already disabled, then the sentence is incorrect.

**Comment by JonathanRosado** [comment]
@soninob I don't think i fully understand the issue. Let's meet and go over it.

**Comment by soninob** [comment]
OK, @JonathanRosado we will take it offline. thanks.

**Comment by soninob** [comment]
@JonathanRosado - The new mockup will supply the additional details.
