### ISSUE TITLE
[UI] - Project view is being corrupted - not sure why

### ISSUE THREAD

**Issue by soninob** [eedevops/shipyard#60]
When playing with the UI, I got the following screen:
![image](https://cloud.githubusercontent.com/assets/2684110/14976036/a11f527a-1110-11e6-98d5-6d75b0cdba16.png)

The toolbar switch location to the right.
Don't know how to replicate it. We need to monitor it if it happens again.

**Comment by soninob** [comment]
Since that time, this defect was replicated a few times.

**Comment by AndreeaDora** [comment]
@soninob This issue was reproduced before our changes and it happens also in the containers view. It  is related to the specific version of Semantic that we use. A solution to solving this issue is to change the version of Semantic which will brake the majority of the views.

**Comment by soninob** [comment]
So, no need for that now.
