### ISSUE TITLE
[Backend] [UI] Update Project Image views and request to use new registry requests and store association with images

### ISSUE THREAD

**Issue by rqc** [eedevops/shipyard#64]
Cross referencing this:

We need to update the Projects UI (in the add image, edit image areas) to use the associated registry id to request repositories, and then later to store that information in the backend to associate the image with the registry. Right now, I see that you send a image.registry field, but that is not implemented in the backend. We need to also add some support for that. Do you care to take a stab at this is @soninob approves? You can also make the tweaks in the backend.

@soninob This is really important since this was functionality that we had before and it broke after docker 1.10. Thanks!

**Comment by rqc** [comment]
@borzamircea when @JonathanRosado arrives tomorrow and if @soninob approves him to work on this,  please meet with @JonathanRosado in case that he needs help with fixing issues in the backend.

**Comment by soninob** [comment]
@rqc, thanks, we are in meeting to understand whats need to be done.
@JonathanRosado, according to our conversation, please continue working with @borzamircea.
thanks!

**Comment by JonathanRosado** [comment]
@rqc I'm not sure i understand the issue. I went ahead and created issues for some defects @borzamircea and i found. Let me know if any of them are related to this one. #65 #67 #68

**Comment by rqc** [comment]
I read the issues. I think you are right on the money with what I found yesterday during testing. I think the API spec never associated the image to a registry, and that is vital to construct the real name of the image (the name should have the preffix for the registry FQDN).

**Comment by borzamircea** [comment]
@rqc: Yesterday, I did add a registry field to an `Image`. Now in the we check if the registry field is empty before pulling an image. If not, we prefix the image `Name` with the `Registry`, and then we proceed with pulling the image. If `Registry` is empty, we pull from `Dockerhub`.

**Comment by borzamircea** [comment]
@rqc , @JonathanRosado @soninob Just finished merging my work from yesyerday with @JonathanRosado 's code. Will continue testing.

**Comment by rqc** [comment]
:+1:

**Comment by borzamircea** [comment]
Now I store the `registryId` and if it is empty I pull from dockerhub else I pull from the registry I get by id and login/pull with the credentials. The `IlmTags` are applied to the `Image` from the `Test`'s `onSuccess` and `onFailure` tags.

```type Image struct {
	ID             string   `json:"id,omitempty" gorethink:"id,omitempty"`
	Name           string   `json:"name" gorethink:"name"`
	ImageId        string   `json:"imageId" gorethink:"imageId"`
	Tag            string   `json:"tag" gorethink:"tag"`
	IlmTags        []string `json:"ilmTags" gorethink:"ilmTags"`
	Description    string   `json:"description" gorethink:"description"`
	RegistryId     string   `json:"registry" gorethink:"registry"`
	Location       string   `json:"location" gorethink:"location"`
	SkipImageBuild bool     `json:"skipImageBuild" gorethink:"skipImageBuild"`
	ProjectId      string   `json:"projectId" gorethink:"projectId"`
}
```

**Comment by rqc** [comment]
OK, if that is enough for now, and you don't think you will need more `Registry` info in the UI or backend, then let's go with it :smile: @JonathanRosado what do you think?

**Comment by JonathanRosado** [comment]
looks good

**Comment by rqc** [comment]
Fixed in  
- #74 
- #76 
- #72 
- #71 
- #70 
- #69 
- #66
