### ISSUE TITLE
[Backend] Cannot pull images from private registry when performing a build

### ISSUE THREAD

**Issue by JonathanRosado** [eedevops/shipyard#68]
As @borzamircea pointed out, we have no way to distinguish between an image that's meant to be pulled from Dockerhub and one that's meant to be pulled from a private registry.

To solve this, we have to send more information to the build entry in the backend. As it is now, it is only sending the image name which is not enough to assert the image's registry.

![image](https://cloud.githubusercontent.com/assets/12142156/15026138/e78f3478-120a-11e6-839b-a6551ad74029.png)

![image](https://cloud.githubusercontent.com/assets/12142156/15026168/1df2e168-120b-11e6-93e7-b9888ec1522a.png)

Some possible solutions:
 - Rather than sending the image name `ubuntu:latest`, send the image name formatted with it's registry to the backend `my-reg-app.com:5000/ubuntu:latest` (as @borzamircea suggested). This solution would be implemented in the frontend.
 - Use the `registryId` field (that's embedded in the image object) to get the missing info (address, port, etc..). This solution would be implemented in the backend.

**Comment by rqc** [comment]
Fixed in #78 and #74
