### ISSUE TITLE
[UI] Slow and blinking UI after triggering several tests one after the other

### ISSUE THREAD

**Issue by edagan** [eedevops/shipyard#83]
Trigger several tests verification one after the other (3-5 are usually enough).
UI flickers annoyingly several time.
Click ILM (or anything else). UI then **hangs **in "waiting" mode. Must refresh to reload and make UI work again. Even then, UI keeps on flickering until all tests are completed.

**Comment by soninob** [comment]
@AndreeaDora - if you have spare time tomorrow, please work on that also.
