### ISSUE TITLE
[UI] - Display named gets deleted after adding provider

### ISSUE THREAD

**Issue by soninob** [eedevops/shipyard#86]
When adding a test and we are filling up "Display Name" before choosing a provider, it gets deleted once chosen.

**Comment by JonathanRosado** [comment]
@soninob This is true of all the fields and is part of the cleanup we do when selecting different providers. I'll go ahead and remove this feature in order to close this issue.

**Comment by soninob** [comment]
@JonathanRosado - the cleanup is due to a bug that we had. The cleanup should stay when we are adding a new test.
The fix should only affect the cleaning of the fields on a "working session".
