### ISSUE TITLE
[UI] - Display results (Clair) using colors 

### ISSUE THREAD

**Issue by soninob** [eedevops/shipyard#88]
When displaying Claire results, to make it more visible to the customer, we can paint the relevant lines with a proper color.
Need to write a parser (for now, let's keep it simple) that will identify the painted lines.
![image](https://cloud.githubusercontent.com/assets/2684110/15144029/965d0b66-16b5-11e6-85a2-13293671615f.png)

**Comment by eitanshp** [comment]
I suggest focusing (for now) on simple "**Low**", "**Medium**" and "**High**" keyword parsing and painting the entire line with a corresponding color (dark **yellow **for **Low**, **orange **for **Medium**, **red **for **High **and overall "**Failure**" status in **red **as well).

**Comment by borzamircea** [comment]
Also, as you guys said, `Failure` --> RED, `Success` --> GREEN

**Comment by rqc** [comment]
You guys think this is high priority? I think this is a nice to have for now.

**Comment by eitanshp** [comment]
@rqc: that's why it's labeled **enhancement** :smile: 
Just a small thing I found out when showcasing it to a potential customer...

**Comment by rqc** [comment]
cool, we didn't have any mocks for that view, but we knew we had to display results in more detail, so it is a WIP :smile:
