### ISSUE TITLE
[Compose] Use default network provided by compose.

### ISSUE THREAD

**Issue by JonathanRosado** [eedevops/shipyard#89]
Right now, we're specifying a custom network via the network key 
![image](https://cloud.githubusercontent.com/assets/12142156/15146757/20a90ec6-168b-11e6-9522-55f9f88d559a.png)
and we're attaching each service to this custom network.
![image](https://cloud.githubusercontent.com/assets/12142156/15146786/41bdb9c2-168b-11e6-8c44-2b8e940a7efb.png)

I don't think this is necessary as Compose creates a `default` network on startup and it's services are, by default, connected to this network. 
If we need to change the name of the network (to avoid collisions) we can use either the `COMPOSE_PROJECT_NAME` environment variable or the `--project-name` flag.

@rqc I bring this up because I've yet to see this pattern in the docs and, although it works, we may not be  using this feature as it was intended. WDYT?

https://docs.docker.com/compose/networking/

**Comment by rqc** [comment]
OK, that's fine. If you want to make a quick pull request, I don't see any problem with it. Please cross-reference it with this issue.
