### ISSUE TITLE
[UI] Add a button for running all tests on a given project

### ISSUE THREAD

**Issue by JonathanRosado** [eedevops/shipyard#99]
As @rqc pointed out, we need a quick and practical way of executing all tests at once (until we decide on how a project and it's tests should be executed).

**Comment by JonathanRosado** [comment]
![image](https://cloud.githubusercontent.com/assets/12142156/15227296/80f3233c-1854-11e6-9d5a-d2d1447f3bfc.png)

![image](https://cloud.githubusercontent.com/assets/12142156/15227336/b47041b8-1854-11e6-85e2-9636c0186863.png)

**Comment by JonathanRosado** [comment]
FYI: running multiple tests at once creates makes the UI flicker. The fix for that is here #97

**Comment by soninob** [comment]
@JonathanRosado - I think that the original idea for this was to use the button from the projects view, choose a project and then press the run button for it.
I can live with that, but please implement it from the projects list also.

**Comment by JonathanRosado** [comment]
@soninob Will do.

**Comment by soninob** [comment]
@JonathanRosado - where are we standing with it, can we close it? is @AndreeaDora has something to do here?

**Comment by soninob** [comment]
Closing this one - we will cover it when we start working on the update spec.
